'use strict';

const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('pamp', {
  listTools: () => ipcRenderer.invoke('tools:list'),
  activate: (toolId, versionName) => ipcRenderer.invoke('tools:activate', toolId, versionName),
  openDir: (toolId) => ipcRenderer.invoke('tools:openDir', toolId),
  statusAll: () => ipcRenderer.invoke('status:all'),
  startService: (toolId) => ipcRenderer.invoke('service:start', toolId),
  stopService: (toolId) => ipcRenderer.invoke('service:stop', toolId),
  getLogs: (toolId) => ipcRenderer.invoke('logs:get', toolId),
  clearLogs: (toolId) => ipcRenderer.invoke('logs:clear', toolId),
  pathStatus: () => ipcRenderer.invoke('path:status'),
  pathSetup: () => ipcRenderer.invoke('path:setup'),
  phpInfo: () => ipcRenderer.invoke('php:info'),
  phpSetExtension: (name, enabled) => ipcRenderer.invoke('php:setExtension', name, enabled),
  phpOpen: (which) => ipcRenderer.invoke('php:open', which),
  composerStatus: () => ipcRenderer.invoke('quick:composerStatus'),
  quickPhpinfo: () => ipcRenderer.invoke('quick:phpinfo'),
  installComposer: () => ipcRenderer.invoke('quick:installComposer'),
  createLaravel: (opts) => ipcRenderer.invoke('quick:createLaravel', opts),
  openPhpMyAdmin: () => ipcRenderer.invoke('quick:pma'),
  onQuickProgress: (fn) => ipcRenderer.on('quick:progress', (_e, payload) => fn(payload)),
  onQuickLog: (fn) => ipcRenderer.on('quick:log', (_e, payload) => fn(payload)),
  getSettings: () => ipcRenderer.invoke('settings:get'),
  setSettings: (patch) => ipcRenderer.invoke('settings:set', patch),
  pickFolder: () => ipcRenderer.invoke('dialog:pickFolder'),
  dlList: (toolId) => ipcRenderer.invoke('dl:list', toolId),
  dlInstall: (toolId, version) => ipcRenderer.invoke('dl:install', toolId, version),
  onDlProgress: (fn) => ipcRenderer.on('dl:progress', (_e, payload) => fn(payload)),
  onLog: (fn) => ipcRenderer.on('service:log', (_e, payload) => fn(payload)),
  minimize: () => ipcRenderer.send('win:minimize'),
  maximize: () => ipcRenderer.send('win:maximize'),
  close: () => ipcRenderer.send('win:close'),
  openExternal: (url) => ipcRenderer.send('shell:openExternal', url),
});
